### ISSUE TITLE
Role of extraction_indices in forward direction

### ISSUE THREAD

**Issue by soerenbrandt** [choderalab/qmlify#10]
Hi Chodera lab,

I am trying to replicate your implementation of qmlify on some sample data and am having difficulty understanding the role of the **extraction_indices** used in the forward direction. As I understand, in the forward direction, the indices are used to extract the positions of the starting positions. However, the size of the positions in the `positions.npz` files are (1, M, N), resulting in different versions of the following error:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-29-8f360d3045d1> in <module>
----> 1 position_extractor(cache_name, 2)

<ipython-input-27-c2adb15d3c20> in position_extractor(positions_cache_filename, index_to_extract)
     29         all_box_vectors = None
     30 
---> 31     positions = all_positions[index_to_extract]
     32     assert positions.shape[
     33         1] == 3, f"the extracted position shapes are: {positions.shape}"

IndexError: index 2 is out of bounds for axis 0 with size 1
```

I assume the size of the all_positions array in `positions.npz` must correspond to the extraction_indices somehow but I don't see how since the variable is not part of the Perses simulation preceding Qmlify where `checkpoint.nc` from which `positions.npz` is generated are created.

I'd really appreciate any insight you can give me into your work. Thank you, Sören.

**Comment by dominicrufa** [comment]
Hi Sören, 
in the current implementation, after forward annealing, each snapshot is saved to a different file, hence 1 in the first dim of the `.npz` position file. _before_ forward annealing, a position `.npz` is extracted from the Perses replica exchange `checkpoint.nc` containing N>1 snapshots. the `perses_extraction_admin` function [here](https://github.com/choderalab/qmlify/blob/f59b48b536fcc8c05cf5205cbca716f343d1d705/qmlify/executables.py#L190) wraps the functionality to extract/store appropriately-indexed snapshots from a perses calculation.

**Comment by soerenbrandt** [comment]
Hi Dominic,
Thanks for the quick reply. As I have it set up, when `perses_extraction_admin` is called, a number of shell-scripts are generated that each call `extract_perses_repex_to_local` to extract the positions from `checkpoint.nc`. During the call for lig0to7, the size of `all_positions = nc_checkpoint.variables['positions']` is **`(1, 11, n_atoms, 3)`** and it is my understanding that those correspond to the number of iid equilibrium states to sample from (which I believe should be larger than 1, right?), the lambda states, number of atoms, and (x,y,z).

* Am I understanding the workflow and implementation of `perses_extraction_admin` correct? 
* In particular, should the size of `nc_checkpoint.variables['positions']` be different since the `position_extractor` will ultimately query those indices? 
* Lastly, which setup options for the Perses MM calculation determine the shape of `nc_checkpoint.variables['positions']`?

Thank you for your help!

EDIT: Adding to my earlier questions: is it required to extend each of the ligXtoY folders manually (as described [here](https://github.com/choderalab/qmlify/tree/master/experiments/mm_data)) to perform qmlify? I was under the impression that step was optional.

**Comment by dominicrufa** [comment]
Hi Sören,

> Am I understanding the workflow and implementation of perses_extraction_admin correct?

mostly, i think. the shape of `all_positions` should be like/be described [here](https://github.com/choderalab/qmlify/blob/f59b48b536fcc8c05cf5205cbca716f343d1d705/qmlify/executables.py#L80). Are you using the tyk 2 data that is in the repo, or are you generating your own? if the 0th axis in your `all_positions` variable is 1, that means only a _single_ repex iteration has saved to disk. 

> Lastly, which setup options for the Perses MM calculation determine the shape of nc_checkpoint.variables['positions']?

I suspect this has to do with the previous answer. you can see  [here](https://github.com/choderalab/qmlify/blob/01abd1c563f37226e41a4ab79a76fff696ff5df6/experiments/mm_data/inputs/ani.yaml#L46) that we are saving positions of each system every 50 iterations of replica exchange with a total number of iterations given [here](https://github.com/choderalab/qmlify/blob/01abd1c563f37226e41a4ab79a76fff696ff5df6/experiments/mm_data/inputs/restart_complex.py#L14).  some details on how openmmtools saves (and lets you query) replica exchange reporters is given [here](https://openmmtools.readthedocs.io/en/0.18.1/api/generated/openmmtools.multistate.MultiStateReporter.html). Given the number of iterations and the save interval, the tyk2 system gets 200 i.i.d. configurations. 

> EDIT: Adding to my earlier questions: is it required to extend each of the ligXtoY folders manually (as described here) to perform qmlify? I was under the impression that step was optional.

there's no reason you have to manually extend each simulation if you don't have wall clock limits on the gpus you are using, but unfortunately, we do (just by iterating over the folders and resubmitting the jobs in a bash line command).

**Comment by soerenbrandt** [comment]
Hi Dominic,

Thanks for clarifying. From looking at the code that's what I was expecting but I wasn't aware that the setup and run of the MD simulation were split due to a wall clock limit. I first thought the extension step was entirely optional.

Thanks for your help!

Best,
Sören
