### ISSUE TITLE
Figure cannot be reproduced with jupyter notebook

### ISSUE THREAD

**Issue by TaizoAyase** [choderalab/qmlify#6]
Hi. I tried to reproduce your figures in the paper and executed the ipynb here.  https://github.com/choderalab/qmlify/blob/master/experiments/free_energy_corrections.ipynb

I got the same plots for the histograms of non-eq work as shown in the notebook, but I cannot reproduce the results of dG and ddG plot like this: 

![ML-MM_absolute](https://user-images.githubusercontent.com/2832924/92883230-a3706c80-f44b-11ea-8bb0-03df130c47e7.png)
![ML-MM_relative](https://user-images.githubusercontent.com/2832924/92883240-a5d2c680-f44b-11ea-8b67-25f0e3ff9b3f.png)
![MM_absolute](https://user-images.githubusercontent.com/2832924/92883243-a66b5d00-f44b-11ea-9404-370c9ecef0ee.png)
![MM_relative](https://user-images.githubusercontent.com/2832924/92883246-a66b5d00-f44b-11ea-890e-2374dd735385.png)

I did not change any cells in the notebook. I'm wondering something wrong with MM data uploaded on github.

**Comment by jchodera** [comment]
@dominicrufa @hannahbrucemacdonald  : Can you look into this and make sure the correct dataset is uploaded?

**Comment by dominicrufa** [comment]
@TaizoAyase , i cloned the repo locally again (master), reran the notebook, and got the _same_ results as the preprint reports again. I am slightly confused with your results as even the "uncorrected" MM relative and absolute free energies do not match the data in the repo. furthermore, there is a relative calculated error (last plot) with an errorbar of ~0.5 kcal/mol, which is not in the data. could you post a `.yml` of your conda env so i can troubleshoot from your end? i may have to provide an `env.yml` with the repo to avoid these problems in the future. thanks for raising the issue.

**Comment by TaizoAyase** [comment]
thank you for quick response!
here is my environment of conda. 

```yaml
name: base
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alabaster=0.7.12=py_0
  - ambermini=16.16.0=7
  - ambertools=18.0=0
  - argon2-cffi=20.1.0=py37h8f50634_1
  - astor=0.8.1=pyh9f0ad1d_0
  - attrs=20.1.0=pyh9f0ad1d_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.1.5=pyh9f0ad1d_0
  - blosc=1.20.0=he1b5a44_0
  - bokeh=2.2.0=py37hc8dfbb8_0
  - boost=1.72.0=py37h9de70de_0
  - boost-cpp=1.72.0=h7b93d67_2
  - brotlipy=0.7.0=py37h8f50634_1000
  - bson=0.5.9=py_0
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.1=py37h2b28604_0
  - cftime=1.2.1=py37h03ebfcd_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.6.0=py_0
  - codecov=2.1.9=pyh9f0ad1d_0
  - conda=4.8.4=py37hc8dfbb8_2
  - conda-package-handling=1.7.0=py37h8f50634_4
  - coverage=5.2.1=py37h8f50634_0
  - cryptography=3.0=py37hb09aad4_0
  - curl=7.71.1=he644dc0_5
  - cycler=0.10.0=py_2
  - cython=0.29.21=py37h3340039_0
  - cytoolz=0.10.1=py37h516909a_0
  - dask=2.24.0=py_0
  - dask-core=2.24.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.24.0=py37hc8dfbb8_0
  - docutils=0.16=py37hc8dfbb8_1
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he1b5a44_2
  - fftw3f=3.3.4=2
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - fsspec=0.8.0=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.65.0=h6f030ca_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=nompi_h3c11f04_101
  - heapdict=1.0.1=py_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.7.0=py37hc8dfbb8_0
  - importlib_metadata=1.7.0=0
  - iniconfig=1.0.1=pyh9f0ad1d_0
  - ipykernel=5.3.4=py37h43977f1_0
  - ipython=7.17.0=py37hc6149b9_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - kiwisolver=1.2.0=py37h99015e2_0
  - krb5=1.17.1=hfafb76e_2
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.34=hc38a660_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=10.0.1=default_hde54327_1
  - libcurl=7.71.1=hcdd3856_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_0
  - libevent=2.1.10=hcdb4288_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libgomp=9.3.0=h24d8f2e_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libllvm10=10.0.1=he513fc3_2
  - libnetcdf=4.7.4=nompi_h84807e1_105
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libpq=12.3=h5513abc_0
  - libsodium=1.0.18=h516909a_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - libxslt=1.1.33=h572872d_1
  - llvmlite=0.34.0=py37h5202443_0
  - locket=0.2.0=py_2
  - lxml=4.5.2=py37he3881c9_0
  - lz4-c=1.9.2=he1b5a44_3
  - lzo=2.10=h516909a_1000
  - markupsafe=1.1.1=py37h8f50634_1
  - matplotlib-base=3.3.1=py37hd478181_1
  - mdtraj=1.9.4=py37h4112681_0
  - mistune=0.8.4=py37h8f50634_1001
  - mock=4.0.2=py37hc8dfbb8_0
  - more-itertools=8.4.0=py_0
  - msgpack-python=1.0.0=py37h99015e2_1
  - mysql-common=8.0.21=0
  - mysql-libs=8.0.21=hf3661c5_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he1b5a44_1
  - networkx=2.5=py_0
  - notebook=6.1.3=py37hc8dfbb8_0
  - nspr=4.28=he1b5a44_0
  - nss=3.56=he751ad9_0
  - numba=0.51.0=py37h9fdb41a_0
  - numexpr=2.7.1=py37h0da4684_1
  - numpy=1.19.1=py37h7ea13bd_2
  - olefile=0.46=py_0
  - openforcefield=0.6.0=py37_1
  - openforcefields=1.2.0=py37_0
  - openmm=7.4.2=py37_cuda101_rc_1
  - openmmforcefields=0.7.4=py_0
  - openssl=1.1.1g=h516909a_1
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.1=py37h3340039_0
  - pandoc=2.10.1=h516909a_0
  - partd=1.1.0=py_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pdbfixer=1.6=py37_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.2.0=py37h718be6c_1
  - pip=20.2.2=py_0
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.13.1=py37hc8dfbb8_2
  - progressbar=2.5=py_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.6=py_0
  - prompt_toolkit=3.0.6=0
  - psutil=5.7.2=py37h8f50634_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.9.0=pyh9f0ad1d_0
  - pybtex=0.22.2=py37hc8dfbb8_1
  - pybtex-docutils=0.2.2=py37hc8dfbb8_1
  - pycairo=1.19.1=py37h01af8b0_3
  - pycosat=0.6.3=py37h8f50634_1004
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h8685d9f_3
  - pyrsistent=0.16.0=py37h8f50634_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - pytables=3.6.1=py37h56451d4_2
  - pytest=6.0.1=py37hc8dfbb8_0
  - pytest-cov=2.10.1=pyh9f0ad1d_0
  - python=3.7.8=h6f2ec95_1_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - qt=5.12.6=h0c8506f_0
  - qtconsole=4.7.6=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - rdkit=2020.03.5=py37h3f38cc2_0
  - readline=8.0=he28a2e2_2
  - requests=2.24.0=pyh9f0ad1d_0
  - ruamel_yaml=0.15.80=py37h8f50634_1001
  - scipy=1.5.2=py37hb14ef9d_0
  - seaborn=0.11.0=0
  - seaborn-base=0.11.0=py_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37hc8dfbb8_0
  - six=1.15.0=pyh9f0ad1d_0
  - smirnoff99frosst=1.1.0=py37_1
  - snappy=1.1.8=he1b5a44_3
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - sphinx=3.2.1=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-bibtex=1.0.0=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.33.0=h4cf870e_0
  - statsmodels=0.12.0=py37h8f50634_0
  - tblib=1.6.0=py_0
  - testpath=0.4.4=py_0
  - tinydb=4.1.1=pyh9f0ad1d_0
  - tk=8.6.10=hed695b0_0
  - toml=0.10.1=pyh9f0ad1d_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h8f50634_1
  - tqdm=4.48.2=pyh9f0ad1d_0
  - traitlets=4.3.3=py37hc8dfbb8_1
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py37hc8dfbb8_1
  - xmltodict=0.12.0=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.2=he1b5a44_3
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1007
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - cerberus==1.3.2
    - clusterutils==0.3.1
    - coddiwomple==0+untagged.48.g6e9e2d5
    - docopt==0.6.2
    - future==0.18.2
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - joblib==0.16.0
    - jupyter==1.0.0
    - lark-parser==0.9.0
    - mpi4py==3.0.3
    - mpiplus==0.0.1+2.ga49d00e
    - netcdf4==1.3.1
    - openmmtools==0.19.0
    - oset==0.1.3
    - pandocfilters==1.4.2
    - parmed==3.2.0
    - parso==0.7.1
    - pymbar==3.0.5
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - scikit-learn==0.23.2
    - sklearn==0.0
    - terminado==0.8.3
    - threadpoolctl==2.1.0
    - torch==1.6.0
    - torchani==2.2
    - torchvision==0.7.0
    - webencodings==0.5.1
prefix: /home/user/.pyenv/versions/miniconda3-4.7.12
```

arsenic, perses, qmlify package is installed vi `pip install -e .` , so not listed above: 
```bash
$ pip freeze
...
-e git+https://github.com/openforcefield/Arsenic.git@0dadc5c5919fdfa8f161abe9763967920ee000b0#egg=arsenic
-e git+https://github.com/choderalab/perses.git@086bd714de51dcd1158f8a6eed2bdc7152d38a68#egg=perses
-e git+https://github.com/choderalab/qmlify.git@3e1d483979d65b947910d31867fc9440513c21b3#egg=qmlify
...
```

**Comment by soerenbrandt** [comment]
Hi @dominicrufa , I ran into similar difficulties replicating Figure 6 using the Jupyter notebook. I found that changing the order of the simulations loaded into the list all_sims significantly alters the distribution in the graph. I couldn’t figure out if this behavior is expected or in what order the simulations should be loaded into the analyze_mlmm function. What's the order on your system?

This is the order of simulations for me and the resultant plot:
```
lig5to0
lig14to8
lig10to13
lig15to14
lig14to9
lig3to0
lig11to14
lig1to13
lig4to14
lig6to0
lig14to2
lig4to5
lig10to6
lig3to13
lig0to7
lig4to12
lig2to7
lig8to0
lig4to13
lig15to4
lig0to12
lig1to6
lig11to0
lig4to9
```
![image](https://user-images.githubusercontent.com/36706786/94214557-b7c25980-fe8e-11ea-92a8-4f5b8dad29e5.png)

![image](https://user-images.githubusercontent.com/36706786/94214531-aed18800-fe8e-11ea-90c4-1a1a1f3eb54b.png)

![image](https://user-images.githubusercontent.com/36706786/94214525-a8431080-fe8e-11ea-8ff0-00ea678e02d4.png)

![image](https://user-images.githubusercontent.com/36706786/94214440-6ade8300-fe8e-11ea-997a-3b7a32cf56b6.png)

I tried sorting the simulations by filename and by ligands resulting in different plots but none are matching your results.

PS: I used a clean conda environment built using the environment (.yml) file I found in the peruses repository.

**Comment by jchodera** [comment]
@soerenbrandt : This is a great clue! Thanks for the detailed reports!

I suspect we're seeing the effects of this potential bug: https://github.com/openforcefield/openforcefield/issues/723

Once we fix that, @dominicrufa should be able to regenerate the pickles (based on an [Ordered Graph](https://networkx.github.io/documentation/stable/reference/classes/ordered.html)) and have the notebook work consistently on other machines.

Thanks for bearing with us, folks, and for the great feedback! This is why we preprint early versions of the work---to get all of this great feedback and help make things more robust and usable before we publish!

@dominicrufa : Can you also check in your `environment.yml` in the meantime? This might also help us identify future issues that result from package version differences.

**Comment by dominicrufa** [comment]
@soerenbrandt , @TaizoAyase , could you try to reproduce the figures with the environment yaml i put [here](https://github.com/choderalab/qmlify/blob/dominicrufa-patch-1/experiments/environment_droplet.yml) (i.e. in the recent [PR](https://github.com/choderalab/qmlify/pull/7) )?

Also, it looks like there are some recent changes to the `arsenic` repository that made recovering even the _uncorrected_ relative free energy scatter plot problematic. In [Arsenic](https://github.com/openforcefield/Arsenic), could you try to `git checkout fe8724f` as a temporary fix while the repo is being fixed up?

**Comment by soerenbrandt** [comment]
@dominicrufa , thanks for the quick reply! I was able to replicate the figures using the jupyter notebook!

I used the `fe8724f` branch for Arsenic though as you suggested.  
I wasn't able to use the environment file you added (I tried but got several packages that couldn't be found). I used the peruses_env.yml file instead (note: plotly and sklearn are not part of that environment and have to be installed separately).

With these modifications, the figures look exactly as in your preprint:

![image](https://user-images.githubusercontent.com/36706786/94325155-e9502900-ff51-11ea-88ef-05608ef4ab84.png)

![image](https://user-images.githubusercontent.com/36706786/94325161-ee14dd00-ff51-11ea-93d4-1c4662e35277.png)

![image](https://user-images.githubusercontent.com/36706786/94325166-f240fa80-ff51-11ea-992d-3e49037f31b1.png)

![image](https://user-images.githubusercontent.com/36706786/94325175-f66d1800-ff51-11ea-9aac-3573490b3400.png)

Thank you!

**Comment by jchodera** [comment]
Quick update: @dominicrufa and @hannahbrucemacdonald have found that there _is_ an issue where the ordering of free energies from the https://github.com/openforcefield/Arsenic package can be incorrect that was recently introduced (in a version after the notebook was created), though it was not quite the potential issue I had identified. While @hannahbrucemacdonald is working on that, @dominicrufa is working on freezing the working environment he had used (#7) until we git this fixed. We'll cut a release for `arsenic` at that time and update the `environment.yml` at that time.

**Comment by jchodera** [comment]
Whoops, I responded before seeing @dominicrufa's response! Glad you got this working! We'll try to make things easier to reproduce!

**Comment by hannahbrucemacdonald** [comment]
Thanks for pointing this out --- also spotting that the order of the results changed the plots --- it was very helpful for figuring out what went wrong.

Now using the latest `Arsenic` master, with https://github.com/choderalab/qmlify/pull/9 the results are consistent with both order of simulation files.


I ~accidentally~ changed arsenic to go from reporting free energies in the order of the ligands, to the order of the nodes (so that you could use a str ligand name), so now there is ambiguity as to what's returned. The experimental values were being assigned based on the order of nodes (which changes when you change the order the edges are added --- when you change the order of simulation results!).


Obviously it's problematic if it's not clear if the calculated values are the order of ligands, or nodes (seeing as I confused myself) so the API for arsenic will change to make this clearer, but I will make sure to change qmlify along with it next time.



Thanks for opening an issue and bearing with us! 👍 :)

**Comment by TaizoAyase** [comment]
@dominicrufa @jchodera @hannahbrucemacdonald 
Thank you for your quick reply, and sorry for my late response.

I can also reproduce the exactly same scatter plots in the notebook `free_energy_corrections.ipynb` .

As @soerenbrandt mentioned above, I cannot create conda environment from the yaml file due to `Solving environment: failed` error. 
But, using `Arsenic` version `fe8724f` is enough to reproduce the results.

Thank you very match!
I'll close this issue as the problem is resolved.
